// Content registry — single source of truth for all classes, subjects, and chapters.
// To add a new class or subject: update the arrays below. No other file needs to change.

import { ClassInfo, SubjectInfo, ClassId, SubjectId, ChapterMeta } from "./types";

export const CLASSES: ClassInfo[] = [
  { id: "class-1", label: "Class 1" },
  { id: "class-2", label: "Class 2" },
  { id: "class-3", label: "Class 3" },
  { id: "class-4", label: "Class 4" },
  { id: "class-5", label: "Class 5" },
  { id: "class-6", label: "Class 6" },
  { id: "class-7", label: "Class 7" },
  { id: "class-8", label: "Class 8" },
  { id: "class-9", label: "Class 9" },
  { id: "class-10", label: "Class 10" },
  { id: "class-11", label: "Class 11" },
  { id: "class-12", label: "Class 12" },
];

export const SUBJECTS: SubjectInfo[] = [
  { id: "maths", label: "Mathematics", icon: "📐", color: "blue" },
  { id: "science", label: "Science", icon: "🔬", color: "green" },
];

// Chapter registry — add chapter metadata here when you create a new chapter
// Content (MDX) lives in /content/[classId]/[subject]/[chapterId]/
export const CHAPTERS: ChapterMeta[] = [
  // Class 1 Maths — NCERT "Joyful Mathematics" textbook (Reprint 2025-26)
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-1-finding-the-furry-cat",
    title: "Finding the Furry Cat!",
    description: "Explore spatial sense — learn about near, far, above, below, left, and right through a fun cat hunt.",
    order: 1,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-2-what-is-long-what-is-round",
    title: "What is Long? What is Round?",
    description: "Identify and compare shapes — long, round, flat, and curved — in objects around you.",
    order: 2,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-3-mango-treat",
    title: "Mango Treat",
    description: "Count objects up to 9, compare groups, and understand more, less, and equal.",
    order: 3,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-4-making-10",
    title: "Making 10",
    description: "Explore number bonds to 10, learn different ways to split and combine numbers.",
    order: 4,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-5-how-many",
    title: "How Many?",
    description: "Count objects in groups, compare quantities, and practise counting up to 20.",
    order: 5,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-6-vegetable-farm",
    title: "Vegetable Farm",
    description: "Introduction to addition and subtraction through a fun vegetable farm story.",
    order: 6,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-7-linas-family",
    title: "Lina's Family",
    description: "Use numbers in real life — counting family members, ages, and everyday situations.",
    order: 7,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-8-fun-with-numbers",
    title: "Fun with Numbers",
    description: "Understand numbers up to 50, place value of tens and ones, and number patterns.",
    order: 8,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-9-utsav",
    title: "Utsav",
    description: "Discover shapes and patterns through Indian festivals — rangoli, kites, and decorations.",
    order: 9,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-10-how-do-i-spend-my-day",
    title: "How Do I Spend My Day?",
    description: "Introduction to time — morning, afternoon, night, and sequencing daily activities.",
    order: 10,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-11-how-many-times",
    title: "How Many Times?",
    description: "Explore repeated addition — counting in groups of 2s, 3s, and 4s through fun activities.",
    order: 11,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-12-how-much-can-we-spend",
    title: "How Much Can We Spend?",
    description: "Introduction to money — recognise coins and notes, and simple buying and selling.",
    order: 12,
  },
  {
    classId: "class-1",
    subject: "maths",
    chapterId: "chapter-13-so-many-toys",
    title: "So Many Toys",
    description: "Collect and organise data — sort, count, and compare groups of objects.",
    order: 13,
  },

  // Class 2 Maths — NCERT "Joyful Mathematics" textbook (Reprint 2025-26)
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-1-a-day-at-the-beach",
    title: "A Day at the Beach",
    description: "Count and compare numbers up to 100, practise skip counting by 2s, 5s, and 10s.",
    order: 1,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-2-shapes-around-us",
    title: "Shapes Around Us",
    description: "Identify 2D and 3D shapes in everyday objects — circles, triangles, rectangles, and cubes.",
    order: 2,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-3-fun-with-numbers",
    title: "Fun with Numbers",
    description: "Explore place value, number names, and ordering numbers up to 200.",
    order: 3,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-4-shadow-story",
    title: "Shadow Story",
    description: "Discover patterns through shadow play — identify, extend, and create repeating patterns.",
    order: 4,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-5-playing-with-lines",
    title: "Playing with Lines",
    description: "Explore straight, curved, horizontal, vertical, and slanting lines through yoga and art.",
    order: 5,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-6-decoration-for-celebration",
    title: "Decoration for Celebration!",
    description: "Addition of 2-digit numbers using tens and ones through festival decoration activities.",
    order: 6,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-7-ranis-gift",
    title: "Rani's Gift",
    description: "Subtraction of 2-digit numbers — take away, find the difference, and solve word problems.",
    order: 7,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-8-grouping-and-sharing",
    title: "Grouping and Sharing",
    description: "Introduction to multiplication and division through equal groups and sharing equally.",
    order: 8,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-9-which-season-is-it",
    title: "Which Season is it?",
    description: "Learn about seasons, months, days of the week, and reading a calendar.",
    order: 9,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-10-fun-at-the-fair",
    title: "Fun at the Fair",
    description: "Work with money — recognise coins and notes, make purchases, and calculate change.",
    order: 10,
  },
  {
    classId: "class-2",
    subject: "maths",
    chapterId: "chapter-11-data-handling",
    title: "Data Handling",
    description: "Collect, sort, and represent simple data using tally marks and pictographs.",
    order: 11,
  },

  // Class 3 Maths — 2024 NCERT "Maths Mela" textbook
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-1-whats-in-a-name",
    title: "What's in a Name?",
    description: "Learn number names, read and write numbers, and understand counting in everyday life.",
    order: 1,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-2-toy-joy",
    title: "Toy Joy",
    description: "Compare and order numbers, understand greater than, less than, and equal to.",
    order: 2,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-3-double-century",
    title: "Double Century",
    description: "Explore numbers up to 200, understand place value of tens and ones, and skip counting.",
    order: 3,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-4-vacation-with-my-nani-maa",
    title: "Vacation with My Nani Maa",
    description: "Learn addition and subtraction of 2-digit numbers through a fun vacation story.",
    order: 4,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-5-fun-with-shapes",
    title: "Fun with Shapes",
    description: "Identify and describe 2D shapes — circles, triangles, rectangles, squares — and their properties.",
    order: 5,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-6-house-of-hundreds-i",
    title: "House of Hundreds — I",
    description: "Extend numbers to 999, understand hundreds-tens-ones place value, and read 3-digit numbers.",
    order: 6,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-7-raksha-bandhan",
    title: "Raksha Bandhan",
    description: "Introduction to multiplication through equal groups, repeated addition, and times tables.",
    order: 7,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-8-fair-share",
    title: "Fair Share",
    description: "Introduction to division — sharing equally, grouping, and the connection to multiplication.",
    order: 8,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-9-house-of-hundreds-ii",
    title: "House of Hundreds — II",
    description: "Add and subtract 3-digit numbers using place value, regrouping, and mental strategies.",
    order: 9,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-10-fun-at-class-party",
    title: "Fun at Class Party!",
    description: "Introduction to fractions — halves, quarters, and thirds — through sharing food and objects.",
    order: 10,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-11-filling-and-lifting",
    title: "Filling and Lifting",
    description: "Explore capacity (how much a container holds) and weight (how heavy things are) through hands-on activities.",
    order: 11,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-12-give-and-take",
    title: "Give and Take",
    description: "Learn about money — coins, notes, buying, selling, and making change in everyday situations.",
    order: 12,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-13-time-goes-on",
    title: "Time Goes On",
    description: "Read clocks, understand hours and minutes, learn days of the week and months of the year.",
    order: 13,
  },
  {
    classId: "class-3",
    subject: "maths",
    chapterId: "chapter-14-the-surajkund-fair",
    title: "The Surajkund Fair",
    description: "Collect, organise, and read simple data using tally marks, tables, and pictographs.",
    order: 14,
  },

  // Class 4 Maths — 2025 NCERT "Maths Mela" textbook
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-1-shapes-around-us",
    title: "Shapes Around Us",
    description: "Explore 2D and 3D shapes, their properties, faces, edges, and corners in everyday objects.",
    order: 1,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-2-hide-and-seek",
    title: "Hide and Seek",
    description: "Discover number puzzles, estimation, and logical thinking through fun hide-and-seek games.",
    order: 2,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-3-pattern-around-us",
    title: "Pattern Around Us",
    description: "Identify, extend, and create repeating and growing patterns in numbers and shapes.",
    order: 3,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-4-thousands-around-us",
    title: "Thousands Around Us",
    description: "Read, write, and compare numbers up to 9,999 using place value and real-life contexts.",
    order: 4,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-5-sharing-and-measuring",
    title: "Sharing and Measuring",
    description: "Understand fractions as equal parts — halves, thirds, fourths — through sharing and measuring.",
    order: 5,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-6-measuring-length",
    title: "Measuring Length",
    description: "Measure and compare lengths using centimetres and metres, and convert between units.",
    order: 6,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-7-the-cleanest-village",
    title: "The Cleanest Village",
    description: "Practice addition and subtraction of larger numbers through the story of a clean village.",
    order: 7,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-8-weigh-it-pour-it",
    title: "Weigh it, Pour it",
    description: "Measure weight in grams and kilograms, and capacity in millilitres and litres.",
    order: 8,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-9-equal-groups",
    title: "Equal Groups",
    description: "Build multiplication and division skills using equal groups, arrays, and times tables.",
    order: 9,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-10-elephants-tigers-and-leopards",
    title: "Elephants, Tigers, and Leopards",
    description: "Read and interpret data from tables and pictographs about wildlife populations.",
    order: 10,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-11-fun-with-symmetry",
    title: "Fun with Symmetry",
    description: "Explore line symmetry and mirror reflections in shapes, letters, and designs.",
    order: 11,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-12-ticking-clocks-and-turning-calendar",
    title: "Ticking Clocks and Turning Calendar",
    description: "Tell time to 5 minutes, calculate duration, and work with calendars, days, and months.",
    order: 12,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-13-the-transport-museum",
    title: "The Transport Museum",
    description: "Solve multiplication and division word problems set in a transport museum context.",
    order: 13,
  },
  {
    classId: "class-4",
    subject: "maths",
    chapterId: "chapter-14-data-handling",
    title: "Data Handling",
    description: "Collect, organise, and represent data using tally marks, tables, pictographs, and bar graphs.",
    order: 14,
  },

  // Class 5 Maths — 2025 NCERT "Maths Mela" textbook
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-1-we-the-travellers-i",
    title: "We the Travellers — I",
    description: "Read, write, and compare large numbers up to 5 digits using place value, rounding, and real-life travel contexts.",
    order: 1,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-2-fractions",
    title: "Fractions",
    description: "Understand fractions as parts of a whole, compare and order fractions, and find equivalent fractions.",
    order: 2,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-3-angles-as-turns",
    title: "Angles as Turns",
    description: "Explore angles through turns and rotations, learn about right angles, and measure angles in degrees.",
    order: 3,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-4-we-the-travellers-ii",
    title: "We the Travellers — II",
    description: "Extend large numbers to lakhs, learn addition and subtraction of 5-digit numbers, and explore estimation.",
    order: 4,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-5-far-and-near",
    title: "Far and Near",
    description: "Measure length and distance using standard units — millimetres, centimetres, metres, and kilometres.",
    order: 5,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-6-the-dairy-farm",
    title: "The Dairy Farm",
    description: "Learn multiplication and division of larger numbers through the context of a dairy farm.",
    order: 6,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-7-shapes-and-patterns",
    title: "Shapes and Patterns",
    description: "Identify and classify 2D and 3D shapes, explore tiling patterns, and understand shape properties.",
    order: 7,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-8-weight-and-capacity",
    title: "Weight and Capacity",
    description: "Measure and compare weight (grams, kilograms) and capacity (millilitres, litres) in everyday situations.",
    order: 8,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-9-coconut-farm",
    title: "Coconut Farm",
    description: "Practice multi-step arithmetic — multiplication, division, and word problems set in a coconut farm context.",
    order: 9,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-10-symmetrical-designs",
    title: "Symmetrical Designs",
    description: "Explore line symmetry and mirror reflections through Indian art, rangoli, and everyday designs.",
    order: 10,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-11-grandmothers-quilt",
    title: "Grandmother's Quilt",
    description: "Discover area and perimeter through quilt patterns — counting squares, comparing shapes, and tiling.",
    order: 11,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-12-racing-seconds",
    title: "Racing Seconds",
    description: "Tell time, convert between hours-minutes-seconds, calculate durations, and read calendars.",
    order: 12,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-13-animal-jumps",
    title: "Animal Jumps",
    description: "Explore multiples, skip counting, and patterns in multiplication through animal jump distances.",
    order: 13,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-14-maps-and-locations",
    title: "Maps and Locations",
    description: "Read simple maps, use directions (N, S, E, W), and describe positions using coordinates and grids.",
    order: 14,
  },
  {
    classId: "class-5",
    subject: "maths",
    chapterId: "chapter-15-data-through-pictures",
    title: "Data Through Pictures",
    description: "Collect, organise, and represent data using pictographs, bar graphs, and tally marks.",
    order: 15,
  },

  // Class 6 Science — 2024 NCERT "Curiosity" textbook
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-1-the-wonderful-world-of-science",
    title: "The Wonderful World of Science",
    description: "Discover what science is, how scientists think, and why curiosity matters.",
    order: 1,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-2-diversity-in-the-living-world",
    title: "Diversity in the Living World",
    description: "Explore the amazing variety of plants, animals, and other living things around us.",
    order: 2,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-3-mindful-eating-a-path-to-a-healthy-body",
    title: "Mindful Eating: A Path to a Healthy Body",
    description: "Learn about nutrients, balanced diet, and how food keeps us healthy.",
    order: 3,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-4-exploring-magnets",
    title: "Exploring Magnets",
    description: "Understand magnets, magnetic properties, and how they are used in daily life.",
    order: 4,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-5-measurement-of-length-and-motion",
    title: "Measurement of Length and Motion",
    description: "Learn how we measure length, distance, and different types of motion.",
    order: 5,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-6-materials-around-us",
    title: "Materials Around Us",
    description: "Explore different materials, their properties, and how we use them every day.",
    order: 6,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-7-temperature-and-its-measurement",
    title: "Temperature and its Measurement",
    description: "Understand what temperature is and how we measure it using thermometers.",
    order: 7,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-8-a-journey-through-states-of-water",
    title: "A Journey through States of Water",
    description: "Learn how water changes between solid, liquid, and gas forms.",
    order: 8,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-9-methods-of-separation-in-everyday-life",
    title: "Methods of Separation in Everyday Life",
    description: "Discover how mixtures are separated using sieving, filtering, evaporation and more.",
    order: 9,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-10-living-creatures-exploring-their-characteristics",
    title: "Living Creatures: Exploring their Characteristics",
    description: "Find out what makes something alive and the characteristics all living things share.",
    order: 10,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-11-natures-treasures",
    title: "Nature's Treasures",
    description: "Understand natural resources, why they matter, and how we should protect them.",
    order: 11,
  },
  {
    classId: "class-6",
    subject: "science",
    chapterId: "chapter-12-beyond-earth",
    title: "Beyond Earth",
    description: "Explore the solar system, stars, planets, and the universe beyond our world.",
    order: 12,
  },

  // Class 6 Maths — 2024 NCERT "Ganita Prakash" textbook
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-1-patterns-in-mathematics",
    title: "Patterns in Mathematics",
    description: "Discover the beauty of patterns — number sequences, geometric shapes, and the art of mathematical thinking.",
    order: 1,
  },
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-2-lines-and-angles",
    title: "Lines and Angles",
    description: "Explore lines, rays, angles, and their properties through drawing and observation.",
    order: 2,
  },
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-3-number-play",
    title: "Number Play",
    description: "Play with numbers — divisibility, Kaprekar's constant, Collatz conjecture, and more surprising number tricks.",
    order: 3,
  },
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-4-data-handling-and-presentation",
    title: "Data Handling and Presentation",
    description: "Learn to collect, organise, and present data using tally marks, pictographs, and bar graphs.",
    order: 4,
  },
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-5-prime-time",
    title: "Prime Time",
    description: "Explore prime numbers, factors, multiples, and the Fundamental Theorem of Arithmetic.",
    order: 5,
  },
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-6-perimeter-and-area",
    title: "Perimeter and Area",
    description: "Understand and calculate the perimeter and area of rectangles, squares, and other shapes.",
    order: 6,
  },
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-7-fractions",
    title: "Fractions",
    description: "Master fractions — representation, comparison, addition, subtraction, and real-life uses.",
    order: 7,
  },
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-8-playing-with-constructions",
    title: "Playing with Constructions",
    description: "Use a compass and ruler to draw angles, bisectors, and geometric figures accurately.",
    order: 8,
  },
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-9-symmetry",
    title: "Symmetry",
    description: "Explore line symmetry and rotational symmetry in shapes, patterns, and nature.",
    order: 9,
  },
  {
    classId: "class-6",
    subject: "maths",
    chapterId: "chapter-10-the-other-side-of-zero",
    title: "The Other Side of Zero",
    description: "Venture into negative numbers — understand integers, the number line, and Brahmagupta's ancient discoveries.",
    order: 10,
  },

  // Class 7 Maths — 2025 NCERT "Ganita Prakash" textbook (Part I + Part II merged)
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-1-large-numbers-around-us",
    title: "Large Numbers Around Us",
    description: "Explore lakhs, crores, millions, and billions — read, write, and compare large numbers in real-life contexts.",
    order: 1,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-2-arithmetic-expressions",
    title: "Arithmetic Expressions",
    description: "Write and evaluate expressions with multiple operations using BODMAS rules without ambiguity.",
    order: 2,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-3-a-peek-beyond-the-point",
    title: "A Peek Beyond the Point",
    description: "Introduction to decimal numbers — place value, addition and subtraction of decimals.",
    order: 3,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-4-expressions-using-letter-numbers",
    title: "Expressions using Letter-Numbers",
    description: "First steps into algebra — use letters for unknown numbers and form algebraic expressions.",
    order: 4,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-5-parallel-and-intersecting-lines",
    title: "Parallel and Intersecting Lines",
    description: "Explore parallel lines, transversals, and angle relationships through paper folding and reasoning.",
    order: 5,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-6-number-play",
    title: "Number Play",
    description: "Puzzles, parity, the Virahanka-Fibonacci sequence, and cryptarithms for computational thinking.",
    order: 6,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-7-a-tale-of-three-intersecting-lines",
    title: "A Tale of Three Intersecting Lines",
    description: "Discover properties of triangles — side lengths, angles, and the triangle inequality through constructions.",
    order: 7,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-8-working-with-fractions",
    title: "Working with Fractions",
    description: "Multiply and divide fractions using Brahmagupta's methods with fresh examples and puzzles.",
    order: 8,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-9-geometric-twins",
    title: "Geometric Twins",
    description: "Understand congruence of plane figures — when are two shapes exactly the same?",
    order: 9,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-10-integers-multiplication-and-division",
    title: "Integers — Multiplication and Division",
    description: "Learn how to multiply and divide positive and negative integers with rules and patterns.",
    order: 10,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-11-finding-common-ground",
    title: "Finding Common Ground",
    description: "Common factors, common multiples, prime factorisation, HCF and LCM.",
    order: 11,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-12-decimals-multiplication-and-division",
    title: "Decimals — Multiplication and Division",
    description: "Extend decimal operations to multiplication and division in practical contexts.",
    order: 12,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-13-connecting-the-dots",
    title: "Connecting the Dots",
    description: "Introduction to central tendency — mean, median, and mode for understanding data.",
    order: 13,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-14-constructions-and-tilings",
    title: "Constructions and Tilings",
    description: "Practical geometry and patterns in shapes — construct figures and explore tiling patterns.",
    order: 14,
  },
  {
    classId: "class-7",
    subject: "maths",
    chapterId: "chapter-15-finding-the-unknown",
    title: "Finding the Unknown",
    description: "Algebra and simple equations — use letters like x and y to find unknown values.",
    order: 15,
  },

  // Class 7 Science — 2025 NCERT "Curiosity" textbook
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-1-the-ever-evolving-world-of-science",
    title: "The Ever-Evolving World of Science",
    description: "An overview of Grade 7 science — how science evolves, connects different fields, and invites curiosity.",
    order: 1,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-2-exploring-substances-acidic-basic-and-neutral",
    title: "Exploring Substances: Acidic, Basic, and Neutral",
    description: "Discover acids, bases, and neutral substances using litmus tests and natural indicators.",
    order: 2,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-3-electricity-circuits-and-their-components",
    title: "Electricity: Circuits and their Components",
    description: "Build electric circuits, understand conductors and insulators, and learn about switches and cells.",
    order: 3,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-4-the-world-of-metals-and-non-metals",
    title: "The World of Metals and Non-metals",
    description: "Explore properties of metals and non-metals — malleability, conductivity, and their everyday uses.",
    order: 4,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-5-changes-around-us-physical-and-chemical",
    title: "Changes Around Us: Physical and Chemical",
    description: "Distinguish between reversible and irreversible changes, and physical vs chemical changes.",
    order: 5,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-6-adolescence-a-stage-of-growth-and-change",
    title: "Adolescence: A Stage of Growth and Change",
    description: "Understand the physical and emotional changes during adolescence and puberty.",
    order: 6,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-7-heat-transfer-in-nature",
    title: "Heat Transfer in Nature",
    description: "Learn about conduction, convection, and radiation — how heat moves through materials.",
    order: 7,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-8-measurement-of-time-and-motion",
    title: "Measurement of Time and Motion",
    description: "Explore sundials, water clocks, speed, distance, and different types of motion.",
    order: 8,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-9-life-processes-in-animals",
    title: "Life Processes in Animals",
    description: "Study nutrition, digestion, and respiration in animals including the human body.",
    order: 9,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-10-life-processes-in-plants",
    title: "Life Processes in Plants",
    description: "Discover how plants make food through photosynthesis and transport water and nutrients.",
    order: 10,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-11-light-shadows-and-reflections",
    title: "Light: Shadows and Reflections",
    description: "Explore how light travels in straight lines, forms shadows, and reflects off surfaces.",
    order: 11,
  },
  {
    classId: "class-7",
    subject: "science",
    chapterId: "chapter-12-earth-moon-and-the-sun",
    title: "Earth, Moon, and the Sun",
    description: "Understand Earth's rotation, phases of the Moon, eclipses, and day-night cycles.",
    order: 12,
  },

  // Class 8 Maths — 2025 NCERT "Ganita Prakash" textbook (Part I + Part II merged)
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-1-a-square-and-a-cube",
    title: "A Square and A Cube",
    description: "Explore square numbers, cube numbers, and their properties through engaging puzzles.",
    order: 1,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-2-power-play",
    title: "Power Play",
    description: "Learn exponents and powers — express very large numbers in compact form.",
    order: 2,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-3-a-story-of-numbers",
    title: "A Story of Numbers",
    description: "Trace the evolution of number systems from ancient civilisations to modern notation.",
    order: 3,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-4-quadrilaterals",
    title: "Quadrilaterals",
    description: "Study interesting types of four-sided figures — parallelograms, rhombi, trapezoids, and their properties.",
    order: 4,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-5-number-play",
    title: "Number Play",
    description: "Discover properties of numbers through engaging activities, visualisation, and mathematical reasoning.",
    order: 5,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-6-we-distribute-yet-things-multiply",
    title: "We Distribute, Yet Things Multiply",
    description: "Explore the distributive law and multiplication patterns through the language of algebra.",
    order: 6,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-7-proportional-reasoning-1",
    title: "Proportional Reasoning — 1",
    description: "Compare quantities using ratios and explore proportional relationships in daily life.",
    order: 7,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-8-fractions-in-disguise",
    title: "Fractions in Disguise",
    description: "Introduction to percentages — understand per cent as fractions out of 100 with practical applications.",
    order: 8,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-9-the-baudhayana-pythagoras-theorem",
    title: "The Baudhayana-Pythagoras Theorem",
    description: "Explore the relationship between side lengths of right-angled triangles from Baudhayana to Pythagoras.",
    order: 9,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-10-proportional-reasoning-2",
    title: "Proportional Reasoning — 2",
    description: "Make pie charts, understand inverse proportions, and extend proportional reasoning skills.",
    order: 10,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-11-exploring-some-geometric-themes",
    title: "Exploring Some Geometric Themes",
    description: "Explore 3D geometry, fractals, and the Sierpinski Carpet — self-similar patterns at smaller scales.",
    order: 11,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-12-tales-by-dots-and-lines",
    title: "Tales by Dots and Lines",
    description: "A new perspective on arithmetic mean and introduction to line graphs for data visualisation.",
    order: 12,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-13-algebra-play",
    title: "Algebra Play",
    description: "Use algebra to model scenarios, investigate number tricks, and solve puzzles.",
    order: 13,
  },
  {
    classId: "class-8",
    subject: "maths",
    chapterId: "chapter-14-area",
    title: "Area",
    description: "Delve deeper into areas of triangles and quadrilaterals using creative approaches.",
    order: 14,
  },

  // Class 8 Science — 2025 NCERT "Curiosity" textbook
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-1-exploring-the-investigative-world-of-science",
    title: "Exploring the Investigative World of Science",
    description: "Enter the investigative world of science — learn to ask questions, design experiments, and think like a scientist.",
    order: 1,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-2-the-invisible-living-world-beyond-our-naked-eye",
    title: "The Invisible Living World: Beyond Our Naked Eye",
    description: "Discover microscopes and the hidden world of microorganisms — bacteria, fungi, and more.",
    order: 2,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-3-health-the-ultimate-treasure",
    title: "Health: The Ultimate Treasure",
    description: "Understand physical, mental, and social well-being — healthy habits, diseases, and prevention.",
    order: 3,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-4-electricity-magnetic-and-heating-effects",
    title: "Electricity: Magnetic and Heating Effects",
    description: "Explore electromagnets, heating effects of current, and how batteries and cells work.",
    order: 4,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-5-exploring-forces",
    title: "Exploring Forces",
    description: "Understand push, pull, friction, gravity, and how forces affect motion in everyday life.",
    order: 5,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-6-pressure-winds-storms-and-cyclones",
    title: "Pressure, Winds, Storms, and Cyclones",
    description: "Learn about atmospheric pressure, wind patterns, and how storms and cyclones form.",
    order: 6,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-7-particulate-nature-of-matter",
    title: "Particulate Nature of Matter",
    description: "Explore how matter is made of tiny particles — solids, liquids, and gases at the particle level.",
    order: 7,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-8-nature-of-matter-elements-compounds-and-mixtures",
    title: "Nature of Matter: Elements, Compounds, and Mixtures",
    description: "Classify matter into elements, compounds, and mixtures and understand their differences.",
    order: 8,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-9-the-amazing-world-of-solutes-solvents-and-solutions",
    title: "The Amazing World of Solutes, Solvents, and Solutions",
    description: "Learn about dissolving, saturation, solubility, and how solutions work in everyday life.",
    order: 9,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-10-light-mirrors-and-lenses",
    title: "Light: Mirrors and Lenses",
    description: "Explore spherical mirrors and lenses — how they form images and their practical applications.",
    order: 10,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-11-keeping-time-with-the-skies",
    title: "Keeping Time with the Skies",
    description: "Understand Moon phases, lunar calendars, and how celestial observations help us keep time.",
    order: 11,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-12-how-nature-works-in-harmony",
    title: "How Nature Works in Harmony",
    description: "Explore ecosystems, food chains, and how living things interact and depend on each other.",
    order: 12,
  },
  {
    classId: "class-8",
    subject: "science",
    chapterId: "chapter-13-our-home-earth-a-unique-life-sustaining-planet",
    title: "Our Home: Earth, a Unique Life Sustaining Planet",
    description: "Discover what makes Earth special — conditions for life, biodiversity, and our responsibility to protect it.",
    order: 13,
  },

  // Class 10 Maths — NCERT "Mathematics" textbook (Reprint 2025-26)
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-1-real-numbers",
    title: "Real Numbers",
    description: "Explore Euclid's division algorithm, the Fundamental Theorem of Arithmetic, and properties of irrational and rational numbers.",
    order: 1,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-2-polynomials",
    title: "Polynomials",
    description: "Study the relationship between zeros and coefficients of polynomials and division algorithm for polynomials.",
    order: 2,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-3-pair-of-linear-equations-in-two-variables",
    title: "Pair of Linear Equations in Two Variables",
    description: "Solve pairs of linear equations using graphical, substitution, elimination, and cross-multiplication methods.",
    order: 3,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-4-quadratic-equations",
    title: "Quadratic Equations",
    description: "Learn to solve quadratic equations by factorisation and the quadratic formula, and explore the discriminant.",
    order: 4,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-5-arithmetic-progressions",
    title: "Arithmetic Progressions",
    description: "Understand AP sequences — find the nth term, sum of n terms, and solve real-life problems.",
    order: 5,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-6-triangles",
    title: "Triangles",
    description: "Study similarity of triangles, criteria for similarity, and apply the Pythagoras Theorem.",
    order: 6,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-7-coordinate-geometry",
    title: "Coordinate Geometry",
    description: "Find distances, midpoints, and section formulas for points in the coordinate plane.",
    order: 7,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-8-introduction-to-trigonometry",
    title: "Introduction to Trigonometry",
    description: "Learn trigonometric ratios (sin, cos, tan) for acute angles and prove trigonometric identities.",
    order: 8,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-9-some-applications-of-trigonometry",
    title: "Some Applications of Trigonometry",
    description: "Apply trigonometry to find heights and distances using angles of elevation and depression.",
    order: 9,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-10-circles",
    title: "Circles",
    description: "Study tangents to a circle, properties of tangents, and solve related problems.",
    order: 10,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-11-areas-related-to-circles",
    title: "Areas Related to Circles",
    description: "Calculate areas of sectors, segments, and combinations of plane figures involving circles.",
    order: 11,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-12-surface-areas-and-volumes",
    title: "Surface Areas and Volumes",
    description: "Find surface areas and volumes of combinations of solids — cones, cylinders, spheres, and more.",
    order: 12,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-13-statistics",
    title: "Statistics",
    description: "Calculate mean, median, and mode of grouped data and draw cumulative frequency curves (ogives).",
    order: 13,
  },
  {
    classId: "class-10",
    subject: "maths",
    chapterId: "chapter-14-probability",
    title: "Probability",
    description: "Understand theoretical probability, compute probabilities of simple events, and solve real-life problems.",
    order: 14,
  },

  // Class 9 Science — NCERT "Science" textbook (Reprint 2025-26)
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-1-matter-in-our-surroundings",
    title: "Matter in Our Surroundings",
    description: "Explore the physical nature of matter — particles, states of matter, and changes between states.",
    order: 1,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-2-is-matter-around-us-pure",
    title: "Is Matter Around Us Pure?",
    description: "Understand mixtures, solutions, suspensions, colloids, and methods of separation.",
    order: 2,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-3-atoms-and-molecules",
    title: "Atoms and Molecules",
    description: "Learn about atoms, molecules, chemical formulae, and the laws of chemical combination.",
    order: 3,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-4-structure-of-the-atom",
    title: "Structure of the Atom",
    description: "Discover electrons, protons, neutrons, and atomic models — from Thomson to Bohr.",
    order: 4,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-5-the-fundamental-unit-of-life",
    title: "The Fundamental Unit of Life",
    description: "Study cells — the basic structural and functional units of all living organisms.",
    order: 5,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-6-tissues",
    title: "Tissues",
    description: "Explore plant and animal tissues — meristematic, permanent, epithelial, connective, muscular, and nervous.",
    order: 6,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-7-motion",
    title: "Motion",
    description: "Understand distance, displacement, speed, velocity, acceleration, and equations of motion.",
    order: 7,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-8-force-and-laws-of-motion",
    title: "Force and Laws of Motion",
    description: "Study Newton's three laws of motion, inertia, momentum, and conservation of momentum.",
    order: 8,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-9-gravitation",
    title: "Gravitation",
    description: "Learn about universal gravitation, free fall, weight vs mass, and Archimedes' principle.",
    order: 9,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-10-work-and-energy",
    title: "Work and Energy",
    description: "Understand work, kinetic energy, potential energy, power, and the law of conservation of energy.",
    order: 10,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-11-sound",
    title: "Sound",
    description: "Explore how sound is produced, travels through media, and learn about echo, resonance, and human ear.",
    order: 11,
  },
  {
    classId: "class-9",
    subject: "science",
    chapterId: "chapter-12-improvement-in-food-resources",
    title: "Improvement in Food Resources",
    description: "Study crop improvement, animal husbandry, fisheries, and bee-keeping for better food production.",
    order: 12,
  },

  // Class 9 Maths — NCERT "Mathematics" textbook (Reprint 2025-26)
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-1-number-systems",
    title: "Number Systems",
    description: "Explore natural numbers, integers, rational and irrational numbers, and real number operations.",
    order: 1,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-2-polynomials",
    title: "Polynomials",
    description: "Study polynomials in one variable, zeroes, remainder theorem, and factor theorem.",
    order: 2,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-3-coordinate-geometry",
    title: "Coordinate Geometry",
    description: "Learn the Cartesian plane, plotting points, and coordinate geometry basics.",
    order: 3,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-4-linear-equations-in-two-variables",
    title: "Linear Equations in Two Variables",
    description: "Understand linear equations in two variables, their solutions, and graphical representation.",
    order: 4,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-5-introduction-to-euclids-geometry",
    title: "Introduction to Euclid's Geometry",
    description: "Study Euclid's definitions, axioms, postulates, and the structure of geometric proofs.",
    order: 5,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-6-lines-and-angles",
    title: "Lines and Angles",
    description: "Explore properties of intersecting and parallel lines, angles, and angle-sum properties.",
    order: 6,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-7-triangles",
    title: "Triangles",
    description: "Learn triangle congruence rules (SSS, SAS, ASA, RHS) and properties of triangles.",
    order: 7,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-8-quadrilaterals",
    title: "Quadrilaterals",
    description: "Study properties of parallelograms, rectangles, rhombuses, squares, and the mid-point theorem.",
    order: 8,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-9-circles",
    title: "Circles",
    description: "Understand circle theorems, chords, arcs, angles subtended, and cyclic quadrilaterals.",
    order: 9,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-10-herons-formula",
    title: "Heron's Formula",
    description: "Apply Heron's formula to find areas of triangles and quadrilaterals using side lengths.",
    order: 10,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-11-surface-areas-and-volumes",
    title: "Surface Areas and Volumes",
    description: "Calculate surface areas and volumes of cubes, cuboids, cylinders, cones, and spheres.",
    order: 11,
  },
  {
    classId: "class-9",
    subject: "maths",
    chapterId: "chapter-12-statistics",
    title: "Statistics",
    description: "Learn data collection, graphical representation, measures of central tendency — mean, median, mode.",
    order: 12,
  },

  // Class 10 Science — NCERT "Science" textbook (Reprint 2025-26)
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-1-chemical-reactions-and-equations",
    title: "Chemical Reactions and Equations",
    description: "Study types of chemical reactions, balancing equations, and effects of oxidation-reduction.",
    order: 1,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-2-acids-bases-and-salts",
    title: "Acids, Bases and Salts",
    description: "Explore properties of acids, bases, and salts, pH scale, and their everyday applications.",
    order: 2,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-3-metals-and-non-metals",
    title: "Metals and Non-metals",
    description: "Learn physical and chemical properties of metals and non-metals, reactivity series, and corrosion.",
    order: 3,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-4-carbon-and-its-compounds",
    title: "Carbon and its Compounds",
    description: "Study covalent bonding, carbon compounds, homologous series, and chemical properties of carbon.",
    order: 4,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-5-life-processes",
    title: "Life Processes",
    description: "Understand nutrition, respiration, transportation, and excretion in living organisms.",
    order: 5,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-6-control-and-coordination",
    title: "Control and Coordination",
    description: "Study nervous system, reflex actions, hormones, and plant coordination mechanisms.",
    order: 6,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-7-how-do-organisms-reproduce",
    title: "How do Organisms Reproduce?",
    description: "Learn modes of reproduction — asexual and sexual — in plants and animals.",
    order: 7,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-8-heredity",
    title: "Heredity",
    description: "Explore Mendel's laws of inheritance, sex determination, and variation during reproduction.",
    order: 8,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-9-light-reflection-and-refraction",
    title: "Light — Reflection and Refraction",
    description: "Study reflection by spherical mirrors, refraction by lenses, and image formation.",
    order: 9,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-10-the-human-eye-and-the-colourful-world",
    title: "The Human Eye and the Colourful World",
    description: "Learn about the human eye, defects of vision, refraction through prisms, and atmospheric phenomena.",
    order: 10,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-11-electricity",
    title: "Electricity",
    description: "Understand electric current, potential difference, Ohm's law, resistance, and power.",
    order: 11,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-12-magnetic-effects-of-electric-current",
    title: "Magnetic Effects of Electric Current",
    description: "Study magnetic fields, electromagnetic induction, electric motors, and generators.",
    order: 12,
  },
  {
    classId: "class-10",
    subject: "science",
    chapterId: "chapter-13-our-environment",
    title: "Our Environment",
    description: "Explore ecosystems, food chains, the ozone layer, and managing waste in our environment.",
    order: 13,
  },
];

// Helper: get all chapters for a specific class + subject
export function getChapters(classId: ClassId, subject: SubjectId): ChapterMeta[] {
  return CHAPTERS
    .filter((c) => c.classId === classId && c.subject === subject)
    .sort((a, b) => a.order - b.order);
}

// Helper: get a single chapter by its ID
export function getChapter(chapterId: string): ChapterMeta | undefined {
  return CHAPTERS.find((c) => c.chapterId === chapterId);
}

// Helper: get subjects that have chapters for a given class
export function getSubjectsForClass(classId: ClassId): SubjectInfo[] {
  return SUBJECTS.filter((s) =>
    CHAPTERS.some((c) => c.classId === classId && c.subject === s.id)
  );
}

// Helper: get classes that have chapters for a given subject
export function getClassesForSubject(subjectId: SubjectId): ClassInfo[] {
  return CLASSES.filter((cls) =>
    CHAPTERS.some((c) => c.classId === cls.id && c.subject === subjectId)
  );
}

// Helper: get class label from ID
export function getClassLabel(classId: ClassId): string {
  return CLASSES.find((c) => c.id === classId)?.label ?? classId;
}

// Helper: get subject label from ID
export function getSubjectLabel(subjectId: SubjectId): string {
  return SUBJECTS.find((s) => s.id === subjectId)?.label ?? subjectId;
}
